/*
Given the CITY and COUNTRY tables, query the names of all cities where the CONTINENT is 'Africa'.

Note: CITY.CountryCode and COUNTRY.Code are matching key columns.

Input Format

The CITY and COUNTRY tables are described as follows: CITY.jpg

Country.jpg
*/

SELECT C.NAME
FROM CITY C
INNER JOIN COUNTRY Y ON C.COUNTRYCODE = Y.CODE AND Y.CONTINENT = 'AFRICA'
ORDER BY NAME;

/* ALMOST SAME */
SELECT C.NAME
FROM CITY C, COUNTRY Y
WHERE C.COUNTRYCODE = Y.CODE AND Y.CONTINENT = 'AFRICA'
ORDER BY NAME;

/* I THINK PERFORMANCE OF PREVIOUS QUERY WILL BE BETTER THAN THIS */
SELECT NAME
FROM CITY
WHERE COUNTRYCODE IN(SELECT CODE FROM COUNTRY WHERE CONTINENT = 'AFRICA' )
ORDER BY NAME;