
SELECT DISTINCT CITY
FROM STATION
WHERE CITY REGEXP '[^AEIOU]$'
ORDER BY CITY ASC;

/* ANOTHER METHOD */
SELECT DISTINCT CITY
FROM STATION
WHERE LOWER(CITY) NOT LIKE ('%a') AND 
      LOWER(CITY) NOT LIKE ('%e') AND
      LOWER(CITY) NOT LIKE ('%i') AND
      LOWER(CITY) NOT LIKE ('%o') AND
      LOWER(CITY) NOT LIKE ('%u') 
ORDER BY CITY ASC;

/* ANOTHER METHOD */
SELECT DISTINCT CITY
FROM STATION
WHERE RIGHT(CITY,1) NOT IN ('A', 'E', 'I', 'O', 'U')
ORDER BY CITY ASC;

/* ANOTHER METHOD */
SELECT DISTINCT CITY
FROM STATION
WHERE SUBSTR(CITY,LENGTH(CITY),1) NOT IN ('A', 'E', 'I', 'O', 'U')
ORDER BY CITY ASC;